weights:
  w1: 1.0
  w2: 2.0
  w3: 1.0
  w4: 1.0

thresholds:
  priority: 16

batch_size_limits:
  min: 10
  max: 100

interval_limits:
  min: 1.0
  max: 10.0

sampling_interval: 5000
processing_interval_base: 100.0

constants:
  alpha: 1.0
  beta: 0.0
  gamma: 1.0
  c: 100.0

static_batch_size: 50
worker_count: 4
